### ISSUE TITLE
Filter or Search pictures by "rating"

### ISSUE THREAD

**Issue by 2beta** [linuxmint/pix#104]
```
 * Pix version (pix --version 2.4.11)
 * Distribution - (Mint 20)
```

**Issue**
I can't find the way to filter/search pictures by "rating".

**Steps to reproduce**
- Right click on a picture.
- In the rating field add a rating (0-5).
- Save.
- No way to filter that.

**Expected behaviour**
In the menu "View" then "Filter. It would be nice to have a field "rating" as filter (like gThumb)

**Comment by icarter09** [comment]
@2beta I put up a PR for this feature request. It works, but something to consider would be for me to look into making the "Rating" filter on how "Size" is being filtered on. Such as "is equal, greater than, and less than" concept, instead of it being filtered on as a string. That'll require a bit more work to change up how the Rating is being saved. Let me know your thoughts. Thanks.

**Comment by 2beta** [comment]
@icarter09 , My idea when I asked for is exactly what you have written : "is equal, greater than, and less than". The same behaviour than gThumb for example

**Comment by icarter09** [comment]
@2beta thanks for reminding me to look at gthumb. I should have done that first thing. Working now on porting that functionality over.
