### ISSUE TITLE
Wish: Support for .webp

### ISSUE THREAD

**Issue by MiDuffy** [linuxmint/pix#151]
```
 * Pix version (pix --version) 2.4.5+Sarah
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint
```

**Issue**
Wish: Display/support for .webp files.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by darkshram** [comment]
Just install `webp-pixbuf-loader` and you will get **webp** support in **pix** and **xviewer**. Packages are available in Debian, Ubuntu, Linux Mint, Fedora, etc. Same for for **jxl**, **heif** and **avif** formats. Just install `jxl-pixbuf-loader`, `heif-pixbuf-loader` and `avif-pixbuf-loader` packages from your distribution software repositories.

**Comment by mtwebster** [comment]
On new isos of Mint, webp-pixbuf-loader should be pre-installed. Others can install as per previous comment.

**Comment by darkshram** [comment]
@butla Support for what you are asking is up to [webp-pixbuf-loader](https://github.com/aruiz/webp-pixbuf-loader), not pix itself (unless you build from source latest master branch, which is based on Gthumb 3.12.2). Pix 2.8.x has no native support for webp, so it completely depends on webp-pixbuf-loader features.

Try upgrading to webp-pixbuf-loader 0.2.2 (will require to build from source, because AFAIK no distributions has packaged yet latest release), or be **patient** and wait for a stable release of next major version of Pix, which will be basically gthumb 3.12 but tailored to be an Xapp. You should also fill am issue at Manjaro to have them upgrade to webp-pixbuf-loader version 0.2.2, which is pretty less buggy an much more feature complete than version 0.0.7.

**Comment by butla** [comment]
@darkshram Ah, you're right. Thanks. Waiting is ok for me here (not that many animated .webp in my library), but I'll add a request to Manjaro forums.
