### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by Pival81** [linuxmint/pix#7]
after reading ````INSTALL```` , i tried doing ````autoconf```` to generate ````configure````, and it exited with this output:
````
configure.ac:13: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:26: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:42: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:101: error: possibly undefined macro: AC_DEFINE
configure.ac:125: error: possibly undefined macro: Awithout saying anythingM_CONDITIONAL
configure.ac:256: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
````
When i tried ````./configure```` it failed with this output:
````
./configure: line 2164: syntax error near unexpected token `1.11'
./configure: line 2164: `AM_INIT_AUTOMAKE(1.11 foreign no-dist-gzip dist-xz tar-ustar subdir-objects)'
````
I'm on arch 64bit

**Comment by ion201** [comment]
The real issue here is that the INSTALL file apparently hasn't been updated since csh was common. This projects configures with:

    gnome-autogen.sh [autoconf args...]

If you manage to "make" successfully on arch, I'd like to know what packages you are using.

**Comment by Pival81** [comment]
i just tried to compile it:
https://paste.ee/p/kFDDY

**Comment by xenopeek** [comment]
pix is based on gThumb 3.2.8, which looks to compile without problems on Arch Linux: https://paste.ee/p/pdKDs

Downloaded gThumb 3.2.8 sources from http://ftp.acc.umu.se/pub/gnome/sources/gthumb/3.2/. Perhaps that can hold a clue why compile of pix fails. It looks like they ran gnome-autogen.sh before creating the archive.

**Comment by ion201** [comment]
I've pinned down this issue. After running configure like so:

`gnome-autogen.sh --prefix=/usr --localstatedir=/var --libexecdir=/usr/lib/pix -disable-static`

Note the creation of this directory:

`% ls 'tests/$(top_srcdir)/pix/.deps' `
`dom_test-dom.Po  glib_utils_test-glib-utils.Po  gsignature_test-gsignature.Po  oauth_test-gsignature.Po`

Obviously, these files are supposed to be in the source root, but end up elsewhere during the configure because of that escaped bash name. Possibly a bug in gnome-autogen.sh? It's not immediately obvious to me what's causing this.

**Comment by ion201** [comment]
I didn't find a "proper" solution (not very familiar with autoconf), but my pkgbuild in the aur now works around this issue to compile.
