### ISSUE TITLE
Hotkeys not working in fullscreen slideshow mode

### ISSUE THREAD

**Issue by pkail** [linuxmint/pix#81]
```
 * Pix version (pix --version)
2.0.3
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Mint 19.1 64-bit Cinnamon
```

**Issue**
Space bar works correctly.  Backspace, page-up and page-down do not.

**Steps to reproduce**
Press the keys above in full-screen mode (f).

**Expected behaviour**
As documented.

**Other information**

**Comment by icarter09** [comment]
Linux Mint 19.2
Pix v2.2.1

I'm able to reproduce this issue for `Backspace` only. The rest of the keys `page-up`, `page-down`, and `space bar` all work correctly.

**Comment by icarter09** [comment]
Linux Mint 19.3
Pix 2.4.3

Still an issue.

**Comment by pkail** [comment]
I'm sorry for the delay in testing this again.
It depends on the order I press them.  If I press F5 to get into slideshow mode and then press PG-UP, PG-UP takes me out of slideshow mode.  Conversely, if I press PG-DOWN I move to the next slide as expected.  If I press PG-DOWN followed by PG-UP,  PG-UP works correctly.

**Comment by icarter09** [comment]
@pkail thanks for the update and no worries on the delay. I can confirm and reproduce your last findings as well.

**Comment by icarter09** [comment]
@pkail after some more experimenting, I don't think the latest issue you brought up is a bug. When in slideshow mode, if you press `PG-UP` on the first image, it ends the slideshow since there is no previous image. The same effect will happen on the last image if you press `PG-DOWN` since there is no more next images. This looks to be more of how slideshow is currently setup rather than a bug. When in fullscreen mode, the buttons do not bail out of the mode, but instead does nothing. If you feel the functionality should be changed up, then a feature request ticket would probably be in order. Let me know your thoughts.

I'll put up a PR to add `Backspace` to the hot keys since it's supposed to work, but currently is not.
